# Generated by Django 3.1.5 on 2021-02-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/categories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('desc', models.TextField(max_length=800)),
                ('quantity', models.IntegerField(default=0)),
                ('specialOffer', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='images/products')),
                ('pubDate', models.DateField()),
                ('category', models.ForeignKey(default='Mobile', on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.category')),
            ],
        ),
    ]
