# Generated by Django 3.1.5 on 2021-02-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('black', 'Black'), ('white', 'White'), ('blue', 'Blue')], default='N/A', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='companyName',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.CharField(choices=[('2', '2GB'), ('3', '3GB'), ('4', '4GB'), ('6', '6GB'), ('8', '8GB'), ('16', '16GB'), ('32', '32GB')], default='N/A', max_length=5),
        ),
        migrations.AddField(
            model_name='product',
            name='specialOfferDesc',
            field=models.TextField(default='N/A', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='storage',
            field=models.CharField(choices=[('16', '16GB'), ('32', '32GB'), ('64', '64GB'), ('128', '128GB'), ('256', '256GB'), ('512', '512GB'), ('1024', '1TB')], default='N/A', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoppingApp.category'),
        ),
    ]
