# Generated by Django 3.1.5 on 2021-02-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0004_auto_20210226_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('red', 'Red'), ('white', 'White'), ('blue', 'Blue')], default='black', max_length=5),
        ),
    ]
