# Generated by Django 3.1.5 on 2021-02-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0005_auto_20210226_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(choices=[('None', 'N/A'), ('2', '2GB'), ('3', '3GB'), ('4', '4GB'), ('6', '6GB'), ('8', '8GB'), ('12', '12GB'), ('16', '16GB'), ('32', '32GB')], default='None', max_length=5),
        ),
    ]
