# Generated by Django 3.1.5 on 2021-02-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0008_auto_20210228_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(choices=[(None, None), ('2GB', '2GB'), ('3GB', '3GB'), ('4Gb', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12Gb', '12GB'), ('16GB', '16GB'), ('32GB', '32GB')], default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(choices=[(None, None), ('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB')], default=None, max_length=5),
        ),
    ]
