# Generated by Django 3.1.5 on 2021-02-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShoppingApp', '0009_auto_20210228_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.CharField(choices=[(None, None), ('2GB', '2GB'), ('3GB', '3GB'), ('4GB', '4GB'), ('6GB', '6GB'), ('8GB', '8GB'), ('12Gb', '12GB'), ('16GB', '16GB'), ('32GB', '32GB')], default=None, max_length=5),
        ),
    ]
